version: '3'

services:
  web:
    hostname: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
      - NEXT_PUBLIC_MAX_DAYS=90
      - API_BASE_URL=http://host.docker.internal:4000
      - SESSION_PASSWORD=sessionpasswordsessionpasswordsessionpassword
    depends_on:
      - api

  api:
    hostname: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    environment:
      - JWT_SECRET=jwtsecretjwtsecretjwtsecret
      - MYSQL_PRIMARY_URL=mysql://userfeedback:userfeedback@host.docker.internal:13307/e2e
      - MYSQL_SECONDARY_URLS=["mysql://userfeedback:userfeedback@host.docker.internal:13307/e2e"]
      - SMTP_HOST=localhost
      - SMTP_PORT=25
      - SMTP_SENDER=abc@feedback.user
      - SMTP_BASE_URL=http://localhost:3000
      - APP_PORT=4000
      - AUTO_MIGRATION=true
      - MASTER_API_KEY=MASTER_API_KEY
      - NODE_OPTIONS="--max_old_space_size=3072"
