version: "3"

services:
  web:
    hostname: web
    build:
      context: ..
      dockerfile: docker/web.dockerfile
    restart: always
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    depends_on:
      - api

  api:
    hostname: api
    build:
      context: ..
      dockerfile: docker/api.dockerfile
    restart: always
    ports:
      - 4000:4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - JWT_SECRET=jwtsecretjwtsecretjwtsecret
      - MYSQL_PRIMARY_URL=mysql://userfeedback:userfeedback@host.docker.internal:13307/e2e
      - SMTP_HOST=localhost
      - SMTP_PORT=25
      - SMTP_SENDER=abc@feedback.user
      - APP_PORT=4000
      - AUTO_MIGRATION=true
      - MASTER_API_KEY=MASTER_API_KEY
      - NODE_OPTIONS="--max_old_space_size=3072"
