services:
  mysql:
    hostname: mysql
    image: mysql:8.4.1
    platform: linux/arm64/v8
    restart: always
    command: [--mysql-native-password=ON]
    environment:
      MYSQL_ROOT_PASSWORD: userfeedback
      MYSQL_DATABASE: userfeedback
      MYSQL_USER: userfeedback
      MYSQL_PASSWORD: userfeedback
      TZ: UTC
    ports:
      - 13306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - app_network

  # optional for e2e test
  mysql-for-e2e:
    hostname: mysql
    image: mysql:8.4.1
    platform: linux/arm64/v8
    restart: always
    command: [--mysql-native-password=ON]
    environment:
      MYSQL_ROOT_PASSWORD: userfeedback
      MYSQL_DATABASE: e2e
      MYSQL_USER: userfeedback
      MYSQL_PASSWORD: userfeedback
      TZ: UTC
    ports:
      - 13307:3306
    volumes:
      - ./volumes/mysql-for-e2e:/var/lib/mysql-for-e2e
    networks:
      - app_network

  # optional for email verification on creating user
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - 5080:80
      - 25:25
      - 143:143
    volumes:
      - ./volumes/smtp4dev:/smtp4dev
    networks:
      - app_network

  # optional for better performance on searching feedbacks
  opensearch-node:
    image: opensearchproject/opensearch:2.14.0
    restart: always
    container_name: opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=userfeedback
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./volumes/opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - app_network

  # optional for opensearch
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    restart: always
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node:9200"]'
      - 'DISABLE_SECURITY_DASHBOARDS_PLUGIN=true'
    depends_on:
      - opensearch-node
    networks:
      - app_network

networks:
  app_network:
