[api]
MYSQL_PRIMARY_URL="mysql://root:userfeedback@host.docker.internal:13306/userfeedback"
# MYSQL_SECONDARY_URLS= ["mysql://root:userfeedback@host.docker.internal:13306/userfeedback"]
OPENSEARCH_USE=true
OPENSEARCH_NODE="http://localhost:9200"
OPENSEARCH_USERNAME="UserFeedback123!@#"
SMTP_HOST="localhost"
SMTP_PORT=25
SMTP_SENDER="noreply@linecorp.com"
SMTP_BASE_URL="http://localhost:3000"
AUTO_MIGRATION=true
NODE_OPTIONS="--max_old_space_size=3072"
BASE_URL="http://localhost:3000"
JWT_SECRET="secret"
OPENSEARCH_PASSWORD="UserFeedback123!@#"
MASTER_API_KEY="MASTER_API_KEY"

[web]
NEXT_PUBLIC_API_BASE_URL="http://localhost:4000"
NEXT_PUBLIC_MAX_DAYS=90
SESSION_PASSWORD="sessionpasswordsessionpasswordsessionpassword"
