[api]
MYSQL_PRIMARY_URL="mysql://root:userfeedback@host.docker.internal:13306/userfeedback"
# MYSQL_SECONDARY_URLS= ["mysql://root:userfeedback@host.docker.internal:13306/userfeedback"]
OPENSEARCH_USE=true
OPENSEARCH_NODE="http://localhost:9200"
OPENSEARCH_USERNAME="UserFeedback123!@#"
OPENSEARCH_PASSWORD="UserFeedback123!@#"

SMTP_HOST="smtp4dev"
SMTP_PORT=25
SMTP_SENDER="noreply@linecorp.com"

AUTO_MIGRATION=true
NODE_OPTIONS="--max_old_space_size=3072"
JWT_SECRET="secret"
MASTER_API_KEY="MASTER_API_KEY"

[web]
NEXT_PUBLIC_API_BASE_URL="http://localhost:4000"
