services:
  web:
    hostname: web
    image: line/abc-user-feedback-web
    restart: always
    ports:
      - 3000:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    depends_on:
      - api

  api:
    hostname: api
    image: line/abc-user-feedback-api
    restart: always
    ports:
      - 4000:4000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MYSQL_PRIMARY_URL=${MYSQL_PRIMARY_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SENDER=${SMTP_SENDER}
      - AUTO_MIGRATION=${AUTO_MIGRATION}
      - MASTER_API_KEY=${MASTER_API_KEY}
      - NODE_OPTIONS=${NODE_OPTIONS}
