services:
  web:
    hostname: web
    image: line/abc-user-feedback-web
    restart: always
    ports:
      - 3000:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    depends_on:
      - api

  api:
    hostname: api
    image: line/abc-user-feedback-api
    restart: always
    ports:
      - 4000:4000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - JWT_SECRET=secret
      - MYSQL_PRIMARY_URL=mysql://root:userfeedback@host.docker.internal:13306/userfeedback
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
      - SMTP_SENDER=noreply@linecorp.com
      - AUTO_MIGRATION=true
      - MASTER_API_KEY=MASTER_API_KEY
      - NODE_OPTIONS=--max_old_space_size=3072
